from pathlib import Path

Import("env")

PROJECT_DIR = Path(env["PROJECT_DIR"])

SVG_PATH = PROJECT_DIR / "ui_preview" / "dashboard-bg.svg"
FONT_PATH = PROJECT_DIR / "ui_preview" / "linebeam.woff2"
OUTPUT_PATH = PROJECT_DIR / "src" / "dashboard_assets.cpp"


def make_raw_cpp_string(content: str, base_delimiter: str) -> str:
    """
    Create a safe C++ raw string.

    The delimiter is expanded if the SVG happens to contain the raw-string
    closing sequence.
    """
    delimiter = base_delimiter

    while f"){delimiter}\"" in content:
        delimiter += "_X"

    return f'R"{delimiter}({content}){delimiter}"'


def format_binary_array(data: bytes, values_per_line: int = 16) -> str:
    values = [f"0x{value:02x}" for value in data]

    lines = []

    for position in range(0, len(values), values_per_line):
        chunk = values[position : position + values_per_line]
        lines.append("    " + ", ".join(chunk))

    return ",\n".join(lines)


def generate_assets() -> None:
    if not SVG_PATH.exists():
        raise FileNotFoundError(f"Missing SVG asset: {SVG_PATH}")

    if not FONT_PATH.exists():
        raise FileNotFoundError(f"Missing font asset: {FONT_PATH}")

    svg_content = SVG_PATH.read_text(encoding="utf-8")
    font_content = FONT_PATH.read_bytes()

    svg_literal = make_raw_cpp_string(
        svg_content,
        "dashboard_svg",
    )

    font_array = format_binary_array(font_content)

    generated_content = f"""// AUTO-GENERATED FILE.
//
// Do not edit this file manually.
// Edit ui_preview/dashboard-bg.svg or ui_preview/linebeam.woff2 instead.

#include "dashboard_assets.h"

const char DASHBOARD_BG_SVG[] PROGMEM = {svg_literal};

const size_t DASHBOARD_BG_SVG_LENGTH =
    sizeof(DASHBOARD_BG_SVG) - 1;

const uint8_t LINEBEAM_WOFF2[] PROGMEM = {{
{font_array}
}};

const size_t LINEBEAM_WOFF2_LENGTH =
    sizeof(LINEBEAM_WOFF2);
"""

    # Avoid rewriting the file when the generated content has not changed.
    # This prevents unnecessary recompilation.
    if OUTPUT_PATH.exists():
        existing_content = OUTPUT_PATH.read_text(encoding="utf-8")

        if existing_content == generated_content:
            print("Dashboard assets are already up to date.")
            return

    OUTPUT_PATH.write_text(
        generated_content,
        encoding="utf-8",
    )

    print(
        f"Embedded dashboard assets: "
        f"{len(svg_content.encode('utf-8'))} SVG bytes, "
        f"{len(font_content)} font bytes"
    )


generate_assets()